#! /usr/bin/env python
# encoding: utf-8

top = '.'
out = '_build'

def options(ctx):
    ctx.add_option('--foo', action='store', default=False, help='Silly test')

def configure(ctx):
    ctx.env.FOO = ctx.options.foo
    ctx.env.CFLAGS = ['-g']
    ctx.env.append_value('CXXFLAGS', ['-02', '-g'])
    ctx.env.append_unique('CFLAGS', ['-g', '-02'])
    ctx.env.prepend_value('CFLAGS', ['-03'])

    ctx.find_program('touch', var='TOUCH')

    print(type(ctx.env))
    print(ctx.env)
    print(ctx.env.FOO)

def build(bld):
    print(bld.env.TOUCH)
    print(bld.env.FOO)
    bld(rule='${TOUCH} ${TGT}', target='foo.txt')
