#! /usr/bin/env python
# encoding: utf-8

top = '.'
out = '_build'

def configure(ctx):
    pass;

def build(ctx):
   ctx(rule='touch ${TGT}', target='foo.txt')
   ctx(rule='cp ${SRC} ${TGT}', source='foo.txt', target='bar.txt')
